### ISSUE TITLE
Can't get oscope to work, fails right on open

### ISSUE THREAD

**Issue by udif** [sgoadhouse/oscope-scpi#1]
Hi,

I can't get oscope to work at all.

Using bare pyvisa seems to work fine:
```
(udif) 4:06pm udif@udif-ce7 udif/oscope-scpi> python3
Python 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvisa as visa
>>> rm = visa.ResourceManager('@py')
>>> l=rm.list_resources()
>>> l
('ASRL/dev/ttyS0::INSTR', 'ASRL/dev/ttyACM1::INSTR', 'ASRL/dev/ttyACM0::INSTR', 'USB0::10893::5988::MY0000000::0::INSTR')
>>> inst=rm.open_resource(l[3])
>>> print(inst.query("*IDN?"))
KEYSIGHT TECHNOLOGIES,DSO-X 3034T,MY0000000,07.20.2017102614
```
(**In this github issue I have erased the true S/N, beginning with MYxxxxxxx, and replaced it with MY0000000**).

When using oscope-scpi, I get errors.
I have the prerequisites:
```
(udif) 3:57pm udif@udif-ce7 udif/oscope-scpi> pip list | grep PyVISA
PyVISA                 1.11.3
PyVISA-py              0.5.2
(udif) 4:04pm udif@udif-ce7 udif/oscope-scpi> python
Python 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from oscope_scpi import Oscilloscope
>>> instr = Oscilloscope('USB0::10893::5988::MY0000000::0::INSTR')
>>> instr = instr.getBestClass()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Vols/vol_design10/lynx/users/udif/oscope-scpi/oscope_scpi/oscilloscope.py", line 114, in getBestClass
    superduper.open()
  File "/Vols/vol_design10/lynx/users/udif/oscope-scpi/oscope_scpi/scpi.py", line 94, in open
    self._inst.clear()
  File "/home/udif/.conda/envs/udif/lib/python3.8/site-packages/pyvisa/resources/resource.py", line 397, in clear
    self.visalib.clear(self.session)
  File "/home/udif/.conda/envs/udif/lib/python3.8/site-packages/pyvisa_py/highlevel.py", line 191, in clear
    return self.handle_return_value(session, sess.clear())
  File "/home/udif/.conda/envs/udif/lib/python3.8/site-packages/pyvisa/highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_NSUP_OPER (-1073807257): The given session or object reference does not support this operation.
```

I don't have much experience with VISA, so please excuse me if this is something trivial I've missed.
As can be seen from the logs, I'm using Keysight DSOX3034T connected through USB on a clean CentOS 7.9 install.

Any help would be appreciated.

Thanks,
Udi

**Comment by sgoadhouse** [comment]
Please run the script `pyvisa-info` and post the results. When PyVISA was installed, its installation should have also installed `pyvisa-info` and it should have been added to your path. A little more info is here: https://pyvisa.readthedocs.io/en/latest/introduction/shell.html#pyvisa-info

**Comment by udif** [comment]
Thanks for your help! The output from `pyvisa-info` is included below.

Also note I have also installed the Keysight VISA 2021 I/O libraries and drivers, hoping it would help.
It doesn't seem to impact direct pyvisa usage, but it didn't help either, when I have used its monitor utilities, I got some strange VI_ERROR_NCIC errors instead, "Not the controller-In-charge".
```
(udif) 4:48pm udif@udif-ce7 udif/dsppower> pyvisa-info
Machine Details:
   Platform ID:    Linux-3.10.0-1160.45.1.el7.x86_64-x86_64-with-glibc2.10
   Processor:      x86_64

Python:
   Implementation: CPython
   Executable:     /home/udif/.conda/envs/udif/bin/python3.8
   Version:        3.8.3
   Compiler:       GCC 7.5.0
   Bits:           64bit
   Build:          Jun  1 2020 17:43:00 (#default)
   Unicode:        UCS4

PyVISA Version: 1.11.3

Backends:
   ivi:
      Version: 1.11.3 (bundled with PyVISA)
      Binary library: Not found
   py:
      Version: 0.5.2
      ASRL INSTR: Available via PySerial (3.5)
      USB INSTR: Available via PyUSB (1.2.1). Backend: libusb1
      USB RAW: Available via PyUSB (1.2.1). Backend: libusb1
      TCPIP INSTR: Available 
      TCPIP SOCKET: Available 
      GPIB INSTR:
         Please install linux-gpib (Linux) or gpib-ctypes (Windows, Linux) to use this resource type. Note that installing gpib-ctypes will give you access to a broader range of funcionality.
         No module named 'gpib'

```

**Comment by sgoadhouse** [comment]
Thanks for the `pyvisa-info` output. It all looks as I expect.

Are you using an external USB hub to connect to the Oscilloscope by chance?

The error message  `Not the controller-In-charge` makes me think that the oscilloscope is configured to use a different interface like perhaps ethernet, if available, or serial or GPIB. Can you check the configuration of the oscilloscope to make sure USB is selected for the SCPI programming interface? I do have a power supply that responds on all ports without having to configure it, so if you do not find a configuration option for this, that is okay. 

I think I have a similar oscilloscope in storage and can check it for the configuration option when I get the chance. Also, knowing what firmware version you have on the oscilloscope may help. I seem to remember that they indicated that they fixed issues in this area in the past few years.

Finally, can you check your version of libusb1? You should be able to find it by executing:

`ldconfig -v | grep libusb`

**Comment by udif** [comment]
Here is my libusb output:
```
	libusbredirparser.so.1 -> libusbredirparser.so.1.0.0
	libusbredirhost.so.1 -> libusbredirhost.so.1.0.0
	libusb-1.0.so.0 -> libusb-1.0.so.0.1.0
	libusbmuxd.so.4 -> libusbmuxd.so.4.0.0
```
I am using a direct USB cable from the back of my machine (a Lenovo desktop with a few years old i7 and 16GB RAM, running CentOS 7).
My scope is not equipped with any optional Ethernet or GPIB connections, and USB is the only communication option available on it.
As for firmware, It seems our scope is indeed not on the latest (we are at 07.20.2017102614, and the current one is 7.40.20210312), however, as I wrote, it seems to respond to direct pyvisa commands just fine. There is something in the upper software layers that's broken (at least on my setup).

Here is a simple code snippet known to be working on my seyup, using raw library calls:
```
...
import pyvisa
...
# instr has been set earlier to the actual instrument address USB0::10893::5988::MYxxxxxxx::0::INSTR
...
        self.rm = pyvisa.ResourceManager()
        res = rm.list_resources()
        if self.instr not in res:
            printf(self.instr, "not found")
            sys.exit(1)
        self.dso = self.rm.open_resource(self.instr)
        self.dso.write(":CHANnel{}:BWLimit 1".format(chan))
        self.dso.write(":CHANnel{}:COUPling DC".format(chan))
        self.dso.write(":CHANnel{}:IMPedance ONEM".format(chan))
...
```
I've played with it, changing values and watching the scope screen getting updated with the value just written.

**Comment by sgoadhouse** [comment]
Hi Udi, thanks for your patience and thanks for emphasizing that it works with direct pyvisa calls. I agree that there must be an issue with some upper level code. I attempt to have the code figure out what model oscilloscope it is talking to and switch classes automatically. That is probably the source of the issue. I will take a look.

**Comment by udif** [comment]
Hi, I have made some progress by simply commenting-out `self._inst.clear()` in scpy.open() . I am now able to get life signs from the scope (query string, etc.).
I;m still getting some lockups after the initial *IDN? response, and I'm looking into that.

I was also wondering about this:
```
oscope.py:263: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (meas is ''):
```

**Comment by udif** [comment]
Apparently something is wrong in checkInstError().

**Comment by udif** [comment]
I think the issue is this:
```
        if (self._version > self._versionLegacy):
            cmd = "SYSTem:ERRor? STR"
            noerr = ("0,", 0, 2)
        else:
            cmd = "SYSTem:ERRor?"
            noerr = ("+0,", 0, 3)
```

I'm running on 7.20, and my unit *definitely* expectes the so called "legacy mode".

I have further consulted the programming manuals currently available on the net:
https://www.keysight.com/us/en/assets/9018-07265/programming-guides/9018-07265.pdf (release 7.35)
https://www.batronix.com/files/Keysight/Oszilloskope/3000XT/3000XT-Programming.pdf (release 2.50)
If you look at pages 1317 and 874 respectively, you will clearly see the expected command is `:SYSTem:ERRor?` . I also verified (on my scope) the returned error code for no error is `+0,"No error"`

**Comment by udif** [comment]
Also, I can't find any references to a keysight `:ANALyze:AEDGes ON` command.

**Comment by sgoadhouse** [comment]
I have pushed some fixes. Yes, the first issue was with the VISA `.clear()` call. For some reason, this is not supported for the USB method but works for TCPIP. I have put appropriate error handling code around it. Although Keysight says to do a `clear()` it may be okay without especially if the resource does not support it.

And you found the same issues I found with `checkInstrErrors()`. I think I have fixed those. It is really disappointing that Keysight changed the SYST:ERR command and the format with a parameter after the `?` must violate SCPI. There is already an official SCPI command to return just an error code. They could have added that instead.

I also created a class for your T suffix model (mine is an older A suffix model). The commands may be different but I am trying to treat them the same until I know differently.

Can you either clone the repo locally or download it with [this link](
https://github.com/sgoadhouse/oscope-scpi/archive/refs/heads/main.zip)?

Then cd into the top level folder and to install, run: `python setup.py install`

If it works, let me know and I will push to PyPi.

**Comment by sgoadhouse** [comment]
> Also, I can't find any references to a keysight `:ANALyze:AEDGes ON` command.

It is in newer instruments like the MXR and UXR series. I use the version number to try to sort it out because it was added along the way. If it is an issue for your T suffix model, we will have to figure out the proper version number to set for the legacy threshold. Let me know if it fails for you.

**Comment by sgoadhouse** [comment]
I just pushed a change to `dso.py` to hopefully force your model to be treated with legacy commands.

**Comment by udif** [comment]
Thanks for all your efforts!
I pulled the latest from your tree and now oscope.py seems to be working fine.
I'm pretty new to SCPI, (I've been mostly just searching for instructions I need and bang them over the I/F),
But I *did* notice that running some modes that uses unsupported instructions may cause timeouts.
For example, running 'python oscope.py -d 1` eventually yields:
```
ERROR(00): -220,"Parameter error", command: ':DVM:MODE FREQ'
ERROR(00): -241,"Hardware missing", command: ':DVM:FREQ?'
ERROR(01): -420,"Query UNTERMINATED", command: ':DVM:FREQ?'
...
...
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

```
Followed by a timeout on my scope.
As I wrote above, I have very little experience with SCPI, but I would assume you shouldn't need a USB timeout to recover from an incorrect command.

**Comment by sgoadhouse** [comment]
Glad I finally got you something working. It helped find a fundamental issue with the code and I am glad that I have it working far more robust than before.

It is not a USB timeout but rather a VISA timeout and that seems to be the nature of how instruments implement SCPI. If it is an unknown query command (i.e. expecting a response) then the device will typically not return anything. Timeout is the only protection against that. You do get the automatic reading of errors from checkInstErrors() so at least you have some reasons for the Timeout. I once had the timeout at 15000 ms but changed it to 5000 ms with this last update which seems plenty. If you want it shorter, you can pass it in when instantiating like so: 
```
    scope = Oscilloscope(pyvisa_oscope,timeout=1000)
```
That will make the timeout 1000 ms.
You can also change it before the call to open() with:
```
   scope._timeout = 1000
```
After the open(), you can change it with:
```
   scope._inst.timeout = 1000
```
This last form is useful if you want a different timeout for a command. You would first save off `scope._inst.timeout` and then set it to your desired timeout. After the command you would restore `scope._inst.timeout` to its original value.

I will give the T suffix its own series name and protected against this situation. 

I have pushed the changes if you want to try them out. If you cloned the repo, then just `git pull`. If you downloaded it, then download again. Then to install, since I did not change the version number, be sure to add the -f option to force the install:

```
python setup.py install -f
```
